name = "TopEdge Ai"

[webhooks]
api_version = "2026-04"

[[webhooks.subscriptions]]
compliance_topics = ["customers/data_request", "customers/redact", "shop/redact"]
uri = "https://chatbot-backend-lg5y.onrender.com/api/shopify/compliance"
