'use strict';

const PDFDocument = require('pdfkit');

function line(doc, y) {
  doc.moveTo(40, y).lineTo(555, y).strokeColor('#E2E8F0').stroke();
}

function sectionTitle(doc, title, y) {
  doc.fillColor('#6d28d9').fontSize(11).font('Helvetica-Bold').text(title, 40, y);
  return y + 18;
}

function fieldRow(doc, label, value, y) {
  doc.fillColor('#64748b').fontSize(9).font('Helvetica-Bold').text(label, 40, y, { width: 120 });
  doc.fillColor('#0f172a').font('Helvetica').text(String(value || '—'), 160, y, { width: 395 });
  return y + 16;
}

/**
 * Stream a formatted GDPR cart-lead export PDF from leadGdpr bundle.
 */
function streamCartLeadGdprPdf(bundle, res, { filename }) {
  const doc = new PDFDocument({ margin: 40, size: 'A4' });
  res.set('Content-Type', 'application/pdf');
  res.set('Content-Disposition', `attachment; filename="${filename}.pdf"`);
  doc.pipe(res);

  const lead = bundle?.records?.AdLead?.[0] || {};
  const orders = bundle?.records?.Order || [];
  const messages = bundle?.records?.Message || [];
  const exportedAt = new Date(bundle?.exportedAt || Date.now()).toLocaleString('en-IN', {
    timeZone: 'Asia/Kolkata',
  });

  doc.fontSize(18).font('Helvetica-Bold').fillColor('#6d28d9').text('TopEdge AI', 40, 40);
  doc.fontSize(11).font('Helvetica').fillColor('#64748b').text('Abandoned cart lead export', 40, 64);
  line(doc, 82);

  let y = 96;
  y = fieldRow(doc, 'Customer', lead.name || 'Guest', y);
  y = fieldRow(doc, 'Phone', lead.phoneNumber || '—', y);
  y = fieldRow(doc, 'Email', lead.email || '—', y);
  y = fieldRow(doc, 'Cart status', lead.cartStatus || '—', y);
  y = fieldRow(doc, 'Cart value', lead.cartValue != null ? `₹${lead.cartValue}` : '—', y);
  y = fieldRow(doc, 'Exported', exportedAt, y);
  line(doc, y + 6);
  y += 20;

  y = sectionTitle(doc, 'Cart snapshot', y);
  const items = lead.cartSnapshot?.items || lead.cartSnapshot?.line_items || [];
  if (Array.isArray(items) && items.length) {
    for (const item of items.slice(0, 12)) {
      const title = item.title || item.name || 'Item';
      const qty = item.quantity || 1;
      const price = item.lineTotal ?? item.price ?? '';
      doc.fillColor('#0f172a').fontSize(9).font('Helvetica')
        .text(`• ${title} (Qty ${qty})${price ? ` — ₹${price}` : ''}`, 48, y, { width: 500 });
      y += 14;
      if (y > 700) {
        doc.addPage();
        y = 40;
      }
    }
  } else {
    doc.fillColor('#94a3b8').fontSize(9).text('No line items stored on lead.', 48, y);
    y += 16;
  }

  y += 8;
  y = sectionTitle(doc, `Orders (${orders.length})`, y);
  if (orders.length) {
    for (const o of orders.slice(0, 8)) {
      doc.fillColor('#0f172a').fontSize(9).font('Helvetica')
        .text(`#${o.orderNumber || o._id} — ₹${o.totalPrice || 0} — ${o.status || '—'}`, 48, y);
      y += 14;
      if (y > 700) {
        doc.addPage();
        y = 40;
      }
    }
  } else {
    doc.fillColor('#94a3b8').fontSize(9).text('No linked orders.', 48, y);
    y += 16;
  }

  y += 8;
  y = sectionTitle(doc, `Messages (${messages.length})`, y);
  if (messages.length) {
    for (const m of messages.slice(0, 20)) {
      const ts = m.createdAt
        ? new Date(m.createdAt).toLocaleString('en-IN', { timeZone: 'Asia/Kolkata' })
        : '';
      const body = String(m.content || m.text || '(media)').slice(0, 200);
      doc.fillColor('#64748b').fontSize(8).text(ts, 48, y);
      doc.fillColor('#0f172a').fontSize(9).text(body, 48, y + 10, { width: 500 });
      y += 28;
      if (y > 680) {
        doc.addPage();
        y = 40;
      }
    }
  } else {
    doc.fillColor('#94a3b8').fontSize(9).text('No messages on file.', 48, y);
    y += 16;
  }

  doc.fontSize(8).fillColor('#94a3b8').text(
    'Confidential — GDPR data export generated by TopEdge AI',
    40,
    760,
    { align: 'center', width: 515 }
  );

  doc.end();
}

module.exports = { streamCartLeadGdprPdf };
