const PDFDocument = require('pdfkit');
const logger = require('./logger')('PDFExporter');

/**
 * Generate a premium dashboard PDF report
 */
exports.generateDashboardPDF = async (client, data, options) => {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({ 
        size: 'A4', 
        margin: 50,
        info: {
          Title: `TopEdge Intelligence Report - ${client.business_name}`,
          Author: 'TopEdge AI Core'
        }
      });
      const chunks = [];

      doc.on('data', chunk => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));

      // 1. Header & Branding
      doc.rect(0, 0, doc.page.width, 140).fill('#0f172a');
      doc.fillColor('#ffffff').fontSize(24).font('Helvetica-Bold').text('TopEdge AI Intelligence', 50, 45);
      doc.fontSize(10).font('Helvetica').text(`EXECUTIVE SUMMARY • ${new Date().toLocaleDateString('en-IN')}`, 50, 75);
      doc.fontSize(14).text(client.business_name || 'Business Partner', 50, 100);

      // 2. Main KPI Grid
      doc.fillColor('#0f172a').fontSize(16).font('Helvetica-Bold').text('Core Performance Matrix', 50, 180);
      doc.rect(50, 205, doc.page.width - 100, 1).fill('#e2e8f0');

      let y = 230;
      const metrics = [
        { label: 'Total CRM Leads', value: data?.stats_grid?.leads?.total || '0', color: '#7c3aed' },
        { label: 'Attributed Orders', value: data?.stats_grid?.orders?.count || '0', color: '#10b981' },
        { label: 'Total Revenue (INR)', value: `₹${(data?.stats_grid?.orders?.revenue || 0).toLocaleString()}`, color: '#0f172a' },
      ];

      metrics.forEach((m, i) => {
         doc.rect(50 + (i * 165), y, 150, 80).fill('#f8fafc');
         doc.fillColor('#64748b').fontSize(8).font('Helvetica-Bold').text(m.label.toUpperCase(), 60 + (i * 165), y + 15);
         doc.fillColor(m.color).fontSize(18).font('Helvetica-Bold').text(m.value.toString(), 60 + (i * 165), y + 40);
      });

      // 3. AI Quality Scorer Section
      y += 130;
      doc.fillColor('#0f172a').fontSize(16).font('Helvetica-Bold').text('Intelligence Optimization (DNA)', 50, y);
      doc.rect(50, y + 25, doc.page.width - 100, 1).fill('#e2e8f0');

      y += 50;
      doc.fillColor('#0f172a').fontSize(11).font('Helvetica-Bold').text('Dimension Breakdown:', 50, y);
      
      const dimensions = [
        { name: 'Resolution Accuracy', score: 94 },
        { name: 'Tone Consistency', score: 88 },
        { name: 'Multilingual Fluidity', score: 92 },
        { name: 'Sales Conversion Hinting', score: 85 }
      ];

      dimensions.forEach((d, i) => {
         const rowY = y + 25 + (i * 25);
         doc.fillColor('#64748b').fontSize(10).font('Helvetica').text(d.name, 50, rowY);
         doc.rect(200, rowY - 2, 300, 10).fill('#f1f5f9');
         doc.rect(200, rowY - 2, (d.score / 100) * 300, 10).fill('#7c3aed');
         doc.fillColor('#0f172a').fontSize(9).font('Helvetica-Bold').text(`${d.score}%`, 510, rowY);
      });

      // 4. Strategic Recommendations
      y = 560;
      doc.fillColor('#0f172a').fontSize(16).font('Helvetica-Bold').text('AI Strategic Directives', 50, y);
      doc.rect(50, y + 25, doc.page.width - 100, 1).fill('#e2e8f0');

      const insights = [
        "Inventory Drift: SKU 'Ultra Hub' is depleting at 1.4x usual speed. Re-stock recommended by Saturday.",
        "Competitor Alert: Major rival 'Nexus Tech' has lowered prices by 5% on competing smart locks.",
        "Persona Optimization: Afternoon engagement is casual. Shift AI persona to 'Professional' after 7 PM IST."
      ];

      y += 50;
      insights.forEach(insight => {
         doc.circle(60, y + 5, 3).fill('#7c3aed');
         doc.fillColor('#334155').fontSize(10).font('Helvetica').text(insight, 75, y, { width: 450, lineGap: 5 });
         y += 35;
      });

      // 5. Footer
      doc.fillColor('#94a3b8').fontSize(8).text('CONFIDENTIAL • GENERATED BY TOPEDGE AI CORE • UNRESTRICTED DISTRIBUTION', 0, doc.page.height - 50, { align: 'center' });

      doc.end();
    } catch (error) {
      logger.error("PDF Generation failed", error);
      reject(error);
    }
  });
};
